SCECcode/pycsep

csep/__init__.py
csep/core/catalog_evaluations.py
csep/core/forecasts.py
csep/core/poisson_evaluations.py
csep/utils/plots.py
csep/utils/readers.py

- 'Normal' -> 'normal' in catalog test results
- update catalog magnitude test to always return a result object even if no observations occur
- added comment to calibration test to make idx selection more clear
- changed default argument for target_event_rates(scale=True -> False)
- added extra parameters to the plot consistency test plot_args function

    minor hotfixes to standard keywords and returns for catalog evaluations

---

csep/core/catalogs.py
tests/test_catalog.py

- added tests for filtering using simple grid
- added test to ensure region midpoints, idx_map, bbox_mask, and origins are the same

fixes issue #80: filter_spatial() not correctly returning region information

---

csep/__init__.py
csep/core/catalogs.py
csep/core/poisson_evaluations.py

- fixes #83 and fixes #94  
- spatial_magnitude_counts() now throws error if magnitude bins are not defined.
- remove default bins in spatial_magnitude_counts()
- CL test and L test now share region with the catalog if not defined
- load_catalog() function now properly handles the apply_filter case where spatial region is not defined

fixes apply_filter and makes CL and L test use the same region as catalog if not defined

---

csep/utils/plots.py

- fixes #109 
- added kwargs to plot_basemap to apply 'fast' projection and central latitude
- added 'fast' as an option to the plot_args of plot_spatial_dataset and plot_catalog
- updated docstrings

missing region border in plots

---

csep/core/catalogs.py
csep/utils/calc.py
tests/test_calc.py
tests/test_catalog.py

- added acceptance tests for these functions
- fixed #116 -- issue with bin1d_vec for scalar values
- fixed #121 -- routing spatial_counts and spatial_magnitude counts through region class

routed spatial_counts and spatial_magnitude_counts through region class

---

csep/utils/plots.py

Addresses an error in the simplification of the latitude-to-longitude aspect calculation, see PR https://github.com/SCECcode/pycsep/pull/110#discussion_r646592443 and issue https://github.com/SCECcode/pycsep/issues/109#issuecomment-855937018.
Sorry for the confusion. (@wsavran: but in this way, I can put it to the test what I just learned minutes ago in your git workshop 😄. Thanks again, Bill!)
(FYI: The whitespace clean-ups were made automatically by my editor)
Ultimately closes #109 (the part with the alternative/fast projection).

Fix simplification of lat-to-lon aspect ratio calculation

---

csep/utils/plots.py

As noted in https://github.com/SCECcode/pycsep/pull/125#issuecomment-857450014, the calculation of the aspect ratio for the 'fast' projection plotting option was still not correct. This PR fixes this.
To summarize:
- original (issue #109): `1 / (LATKM / 111.320 * np.cos(np.deg2rad(lat_region)))` -- WRONG (but almost correct)
- simplification (PR #110): `111.320 * np.cos(np.deg2rad(lat_region)) / LATKM` -- VERY WRONG
- simplification (PR #125): `111.320 / LATKM / np.cos(np.deg2rad(lat_region))` -- WRONG (but almost correct)
- correct (this PR) `LATKM / (111.320 * np.cos(np.deg2rad(lat_region)))`
Apologies for the multiple confusions! Next time, I will do the maths first... 😉

Fix lat-to-lon aspect ratio (now for real)

---

csep/utils/plots.py

Added customizable confidence interval to poisson plots

poisson plot confidence interval

---

csep/utils/plots.py

Added customization options to plot_comparison_test, similar to those one of Poisson_consistency tests,  and added functionality to plot simultaneously a list of w-test if provided.    T-test bars are coloured by significance (green is sign. better, red if sign.worse and gray if not significant.   W-test significance is shown with a filled marker at the mean IG.    
However, this needs an example/tutorial so the "legend" can be explained.

Modified comparison plot, to plot simultaneously T and W tests

---

csep/core/regions.py
csep/utils/plots.py

@pabloitu do you mind taking a look at this pr when you have a chance?
contains a few adjustments to the plotting utilites
* draw region border correctly
* properly scale axes for comparison test plots
* allow chaining for consistency test plots

contains hotfixes for plotting utilities

---

csep/core/catalogs.py
csep/utils/plots.py

The magnitude ticks defined as default in catalog.plot() were spurious, and created problems if the magnitude range of the catalog was not in a similar range. The default now for magnitude legend elements are numpy.linspace(min(mw_range), max(mw_range), 4).   Rounding of the magnitude is to one decimal, but only in the legend text. Raise a warning, if the passed magnitude_ticks are outside of the catalog mw range.

Fixed catalog plotting options.

---

csep/core/catalogs.py
csep/core/forecasts.py
csep/core/regions.py
csep/models.py
tests/test_catalog.py
tests/test_spatial.py

moved polygon class to models module.

refactor polygon to models module

---

csep/core/catalog_evaluations.py
csep/core/forecasts.py
csep/utils/plots.py
tests/test_forecast.py

added verbose option to catalog based tests
added get_event_counts method to CatalogForecast
added plotting arguments for more granular customization

Adds option called get_event_counts to CatalogForecast and adds arguments to plotting functions

---

csep/utils/plots.py
examples/tutorials/plot_customizations.py

Fixes #144. Modified plot_spatial_dataset and plot_catalog to correctly handle Global plots. Updated plot_customizations example in the docs.
- [*] Bug fix (non-breaking change which fixes an issue)
- [*] Documentation update (this pull request adds no new code)
- [* ] I have performed a self-review of my own code
- [*] I have made corresponding changes to the documentation

Fix to global plots

---

examples/tutorials/gridded_forecast_evaluation.py

added example plots to gridded_forecast_example.py

added documentation for roc and i1 score

---

notebooks/CSEP_tests.ipynb

added test notebook with theory and examples for pycsep tests

added CSEP_tests.ipynb

---

csep/core/forecasts.py
csep/core/regions.py
csep/utils/plots.py

Fixed dh issue by modifying get_bbox()

---

csep/core/regions.py
csep/utils/readers.py

quadtree csv reader

---

csep/core/forecasts.py
csep/core/regions.py
requirements.txt
requirements.yml
setup.py

fixes #197.  Now uses shapely to merge all cell polygons into one, and extract the borders. Floating point issues with coincident cell edges are sorted out by rounding up to 2 decimals.
Fixes issue #197 #200.

fix: region border plot

---

csep/__init__.py
csep/utils/comcat.py
csep/utils/readers.py
docs/reference/api_reference.rst
examples/tutorials/catalog_filtering.py
tests/artifacts/BSI/vcr_search.yaml
tests/artifacts/BSI/vcr_summary.yaml
tests/test_bsi.py

created function to query the Bollettino Sismico Italiano (BSI) `webservices.rm.ingv.it`.  It is modified from the query comcat functions. Minor mods were done to cat_query functions to handle the different properties returned from bsi compared to comcat (e.g. event['id'] in comcat, event['properties']['eventId'] in bsi). 

feat: Added query_bsi

---

csep/core/binomial_evaluations.py
tests/test_evaluations.py

Binomial testing

---

csep/utils/plots.py
requirements.txt
requirements.yml
setup.py

fixes #203.  Replaces the use of the observed statistic to plot confidence intervals by using error plots. Instead, uses the mean of the distribution, whereas the observed statistic if plot separately.  Also, provides the option to plot the mean as a black dot. This change fixes the issue, while I expect to refactor the plotting code for version 0.7.0

Fix consistency plots

---

csep/__init__.py
csep/core/catalogs.py
csep/utils/geonet.py
csep/utils/readers.py
tests/artifacts/geonet/vcr_search.yaml
tests/artifacts/geonet/vcr_summary.yaml
tests/test_gns.py

Added NZ catalog reader

---

csep/__init__.py
csep/utils/iris.py
csep/utils/readers.py
tests/artifacts/gCMT/vcr_search.yaml
tests/artifacts/gCMT/vcr_summary.yaml
tests/test_gcmt.py

Added gcmt accessor from ISC API.  Follows the same logic than comcat and bsi readers. Created test for an event search and summary info from a request.

gCMT Catalog accessor

---

csep/utils/comcat.py

The handling of exceptions to query the Italy BSI catalog (due to SSL certificates not being quite alright on their API) must be different from python  3.8 and 3.11 In 3.8, the reason is thrown as a ssl.SSLCertVerificationErros, whereas in 3.11 it is thrown just as a ssl.SSLError, both of which has different codes or error numbers. 
Fixed that issue, to the query works for python versions from 3.8 up to 3.11

fix: handles BSI query URL exception or SSL errors for python 3.8 to 3.11

---

csep/core/catalogs.py

**Problem**: on Windows, `csep.catalogs.AbstractBaseCatalog.write_ascii()` interleaves every entry with an empty line, like so.:
```
lon,lat,mag,time_string,depth,catalog_id,event_id
-115.2228333,32.3463333,3.99,2005-01-02T20:58:48.280000,5.987,,ci10070917
-117.4448333,34.1238333,4.42,2005-01-06T14:35:27.680000,6.148,,ci14116972
```
Those files can also not be read by `csep.load_catalog()` (`IndexError: list index out of range`)
**Solution**: add `newline=''` to `open(filename, write_string)`, see [docs.python.org/3/library/csv (footnote)](https://docs.python.org/3/library/csv.html#id3) and [stackoverflow.com/a/3348664](https://stackoverflow.com/a/3348664)
**FYI**: `.write_json()` is not affected, and there is no further occurrence in pyCSEP that needs to be fixed (b/c there is no further …

Fix writing catalog csv files on Windows

---

csep/utils/time_utils.py
tests/test_time_utilities.py

Added a bypass of time_utils for Windows OS users, which creates datetime objects from negative timestamps/epochs.

Fixed negative timestamps parsing for windows

---

.github/workflows/publish-pypi.yml

ci: changed environment build of pypi-publish from miniconda to micromamba

---

csep/utils/plots.py

Fixes #236 typo/error in poisson_consistency_test that made negativebinomial critical intervals being reversely assigned, thus creating error with matplotlib.

fix: negbinom consistency plots now have the correct boundaries

---

csep/utils/plots.py

removed shading when less than 3 forecasts

---

docs/getting_started/installing.rst

docs: Fixed #234  command instruction to install pycsep with pytest and sphinx dependencies

docs: developer installation 

---

.github/workflows/build-test.yml
tests/test_JmaCsvCatalog.py

Addresses #237 
Tested the GA on my fork and works ok!
ga: added only windows 3.10
ga: updated github actions to test windows. fix jma tests
ga: reverted to run GA on maaster(main) branch & fork

Added windows-tests on github actions

---

csep/utils/plots.py

closes #264 
fix: changed scipy.integrate.cumtrapz import by cumulative_trapezoid …in plots.py module
Fixes issue #264.

Fix dependency error from scipy

---

csep/core/catalogs.py
csep/core/forecasts.py
csep/core/regions.py
csep/utils/calc.py
tests/test_calc.py
tests/test_regions.py

⚠ Caution, longer treatise ahead! 🤷‍♂️
I [previously proposed a preliminary fix](https://github.com/SCECcode/pycsep/issues/255#issuecomment-2548687127) based on rounding the estimated bin size `h`. But there's a more elegant [fix](https://github.com/SCECcode/pycsep/commit/e12f6a0):
```diff
-    h_tol = numpy.abs(h) * numpy.finfo(numpy.float64).eps
+    h_tol = a0_tol
```
in [this line](https://github.com/SCECcode/pycsep/blob/2feb9148/csep/utils/calc.py#L83).
This change is sufficient because the prior floating-point operation `h = bins[1] - bins[0]` in the [previous line](https://github.com/SCECcode/pycsep/blob/2feb9148/csep/utils/calc.py#L83) carries the unit [roundoff error](https://en.wikipedia.org/wiki/Round-off_error) of the involved numbers (and may introduce a further roundoff …

Fix and optimize `bin1d_vec` + extend units tests + fix imprecise bin edge creation
